TheUltimateGamingPlatform.Web/Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TheUltimateGamingPlatform.Database.Repository.Interfaces;
using TheUltimateGamingPlatform.Model;
using TheUltimateGamingPlatform.Web.Repositories;

namespace TheUltimateGamingPlatform.Web.Pages;

public class CartModel(
    IRepositoryCart repositoryCart,
    IRepositoryUser repositoryUser,
    IRepositoryGame repositoryGame, 
    CartGameRepository cartGameRepository) : PageModel
{
    public List<Game>? Games { get; set; }
    public decimal SumProduct { get; set; }

    private User? user;
    public async Task OnGetAsync()
    {
        user = await repositoryUser.GetByIdAsync(1);
        Games = cartGameRepository.Games;
        SumProduct = cartGameRepository.Games.Sum(game => game.Price);
    }

    public void OnPostDeleteGame(int id)
    {
        var game = cartGameRepository.Games.Single(game => game.Id == id);
        cartGameRepository.Games.Remove(game);
    }

    public async Task<IActionResult> OnPostCreateOrder()
    {
        var user = await repositoryUser.GetByIdAsync(1);
        var listId = cartGameRepository.Games.Select(x => x.Id).ToList();
        var games = await repositoryGame.GetGamesByListId(listId);
        
        var cart = new Cart
        {
            DatePurchase = DateOnly.FromDateTime(DateTime.Now),
            Sum = cartGameRepository.Games.Sum(game => game.Price),
            User = user,
            Games = games
        };

        await repositoryCart.AddAsync(cart);

        cartGameRepository.Games.Clear();
        
        return RedirectToPage("/Index");
    }
}

TheUltimateGamingPlatform.Web/Pages/GameDetails.cshtml.cs
using TheUltimateGamingPlatform.Model;
using TheUltimateGamingPlatform.Database.Repository.Interfaces;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TheUltimateGamingPlatform.Web.Repositories;
using Microsoft.AspNetCore.Mvc;
using TheUltimateGamingPlatform.Database;
using Microsoft.EntityFrameworkCore;

namespace TheUltimateGamingPlatform.Web.Pages;

public class GameDetailsModel(IRepositoryGame repositoryGame, IRepositoryUser repositoryUser, CartGameRepository cartGameRepository, TheUltimateGamingPlatformContext context) : PageModel
{
    public Game? Game { get; set; }
    public bool IsContainsInCart { get; set; }
    public bool IsPurchased { get; set; }
    public bool IsWishList { get; set; }
    public async Task OnGetAsync(int id)
    {
        IsContainsInCart = cartGameRepository.Games
            .Where(x => x.Id == id)
            .Any();

        var user = await context.Users
            .Include(x => x.Games)
            .SingleAsync(x => x.Id == 1);

        IsWishList = user.Games.Where(x => x.Id == id).Any();

        IsPurchased = await repositoryUser.IsPurchasedGameAsync(id, 1);

        Game = await repositoryGame.GetDetailsAsync(id);
    }

    public async Task<IActionResult> OnPostAsync(int id)
    {
        var game = await repositoryGame.GetByIdAsync(id);
        cartGameRepository.Games.Add(game);

        return RedirectToPage("/Cart");
    }

    public async Task<IActionResult> OnPostAddWishList(int id)
    {
        await repositoryUser.AddGameWishListAsync(id, 1);

        return RedirectToPage("/Shop/WishList");
    }
}

TheUltimateGamingPlatform.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using TheUltimateGamingPlatform.Database.Repository.Interfaces;
using TheUltimateGamingPlatform.Model;

namespace TheUltimateGamingPlatform.Web.Pages;

public class IndexModel(IRepositoryGame repositoryGame) : PageModel
{
    public List<Game> Games { get; set; } = [];
    public async Task OnGetAsync()
    {
        Games = await repositoryGame.GetAllAsync();
    }
}

TheUltimateGamingPlatform.Web/Pages/Library.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using TheUltimateGamingPlatform.Database.Repository.Interfaces;
using TheUltimateGamingPlatform.Model;

namespace TheUltimateGamingPlatform.Web.Pages;

public class LibraryModel(IRepositoryGame repositoryGame) : PageModel
{
    public List<Game> Games { get; set; } = [];

    public async Task OnGetAsync()
    {
        Games = await repositoryGame.GetGamesByUserId(1);
    }
}

TheUltimateGamingPlatform.Web/Pages/Profile.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TheUltimateGamingPlatform.Web.Pages;

public class ProfileModel : PageModel
{
    public void OnGet()
    {
    }
}

TheUltimateGamingPlatform.Web/Pages/Shop/PopularGames.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TheUltimateGamingPlatform.Database;
using TheUltimateGamingPlatform.Model;

namespace TheUltimateGamingPlatform.Web.Pages.Shop;

public class PopularGamesModel(TheUltimateGamingPlatformContext context) : PageModel
{
    public List<Game>? Games { get; set;  }
    public async Task OnGetAsync()
    {
        var dictionary = new Dictionary<Game, int>();

        var carts = await context.Carts.Include(x => x.Games).Where(
            x => x.DatePurchase >= DateOnly.FromDateTime(DateTime.Now.AddMonths(-1))).ToListAsync();

        foreach (var car in carts)
        {
            foreach (var game in car.Games)
            {
                if (!dictionary.TryGetValue(game, out int value))
                {
                    dictionary.Add(game, 1);
                }
                else
                {
                    dictionary[game] = ++value;
                }
            }
        }

        var sortedDict = (from entry in dictionary orderby entry.Value ascending select entry).ToDictionary();

        Games = new List<Game>(sortedDict.Keys);
    }
}

TheUltimateGamingPlatform.Web/Pages/Shop/RecommendationGames.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using TheUltimateGamingPlatform.Database;
using TheUltimateGamingPlatform.Model;

namespace TheUltimateGamingPlatform.Web.Pages.Shop;

public class RecommendationGamesModel(TheUltimateGamingPlatformContext context) : PageModel
{
    public HashSet<Game>? Games { get; set; }
    public async Task OnGetAsync()
    {
        var resultGames = new HashSet<Game>();
        var idGenres = new HashSet<int>();

        var user = await context.Users
            .Include(x => x.Games)
            .ThenInclude(x => x.Genres)
            .SingleAsync(x => x.Id == 1);

        var carts = await context.Carts
            .Include(x => x.Games)
            .ThenInclude(x => x.Genres)
            .Include(x => x.User)
            .Where(x => x.User.Id == 1)
            .ToListAsync();

        foreach ( var cart in carts )
        {
            foreach (var game in cart.Games)
            {
                foreach (var genre in game.Genres)
                {
                    if (!idGenres.Contains(genre.Id))
                    {
                        idGenres.Add(genre.Id);
                    }
                }
            }
        }

        foreach (var game in user.Games)
        {
            var listId = game.Genres.Select(x => x.Id);

            foreach (var id in listId)
            {
                if (listId.Contains(id))
                {
                    idGenres.Add(id);
                }   
            }
        }


        var games = context.Games.Include(x => x.Genres);
        var resGames = new HashSet<Game>();
        foreach (var game in games)
        {
            foreach (var genre in game.Genres)
            {
                if (idGenres.Contains(genre.Id))
                {
                    resGames.Add(game);
                }
            }
        }

        Games = resGames;
    }
}

TheUltimateGamingPlatform.Web/Pages/Shop/WishList.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using TheUltimateGamingPlatform.Database.Repository.Interfaces;
using TheUltimateGamingPlatform.Model;

namespace TheUltimateGamingPlatform.Web.Pages.Shop;

public class WishListModel(IRepositoryUser repositoryUser) : PageModel
{
    public List<Game>? Games { get; set; }

    public async Task OnGetAsync()
    {
        Games = await repositoryUser.GetGamesWishListAsync(1);
    }
}

TheUltimateGamingPlatform.Web/Pages/Cart.cshtml
@page
@model TheUltimateGamingPlatform.Web.Pages.CartModel

<section class="h-100 h-custom" style="background-color: #eee;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col">
                <div class="card">
                    <div class="card-body p-4">
                        <div class="row">
                            <div class="col-lg-7">
                                <h5 class="mb-3">
                                    <a href="#!" class="text-body">
                                        Продолжить покупки
                                    </a>
                                </h5>
                                <hr>
                                <div class="d-flex justify-content-between align-items-center mb-4">
                                    <div>
                                        <p class="mb-1">Ваша корзина</p>
                                    </div>
                                </div>

                                @if (Model.Games is null)
                                {
                                    <h1>Товаров в корзине нет</h1>
                                }
                                else
                                {
                                    @foreach (var game in Model.Games)
                                    {
                                        <div class="card mb-3">
                                            <div class="card-body">
                                                <div class="d-flex justify-content-between">
                                                    <div class="d-flex flex-row align-items-center">
                                                        <div>
                                                            <img src="@game.PreviewImg"
                                                                 class="img-fluid rounded-3" alt="@game.Title" style="width: 65px;">
                                                        </div>
                                                        <div class="ms-3">
                                                            <h5>@game.Title</h5>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex flex-row align-items-center">
                                                        <div style="width: 90px;">
                                                            <h5 class="mb-0">@game.Price р</h5>
                                                        </div>

                                                        <form method="post" asp-page-handler="DeleteGame">
                                                            <input type="hidden" name="id" value="@game.Id" />
                                                            <input type="submit" class="btn btn-danger" value="Удалить" />
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    }
                                }
                            </div>
                            <div class="col-lg-5">

                                <div class="card bg-primary text-white rounded-3">
                                    <div class="card-body">
                                        <div class="d-flex justify-content-between align-items-center mb-4">
                                            <h5 class="mb-0">Card details</h5>
                                            <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/avatar-6.webp"
                                                 class="img-fluid rounded-3" style="width: 45px;" alt="Avatar">
                                        </div>

                                        <p class="small mb-2">Card type</p>
                                        <a href="#!" type="submit" class="text-white">
                                            <i class="fab fa-cc-mastercard fa-2x me-2"></i>
                                        </a>
                                        <a href="#!" type="submit" class="text-white">
                                            <i class="fab fa-cc-visa fa-2x me-2"></i>
                                        </a>
                                        <a href="#!" type="submit" class="text-white">
                                            <i class="fab fa-cc-amex fa-2x me-2"></i>
                                        </a>
                                        <a href="#!" type="submit" class="text-white"><i class="fab fa-cc-paypal fa-2x"></i></a>

                                        <form class="mt-4" method="post" asp-page-handler="CreateOrder">
                                            <div data-mdb-input-init class="form-outline form-white mb-4">
                                                <input type="text" id="typeName" class="form-control form-control-lg" siez="17"
                                                       placeholder="Cardholder's Name" />
                                                <label class="form-label" for="typeName">Cardholder's Name</label>
                                            </div>

                                            <div data-mdb-input-init class="form-outline form-white mb-4">
                                                <input type="text" id="typeText" class="form-control form-control-lg" siez="17"
                                                       placeholder="1234 5678 9012 3457" minlength="19" maxlength="19" />
                                                <label class="form-label" for="typeText">Card Number</label>
                                            </div>

                                            <div class="row mb-4">
                                                <div class="col-md-6">
                                                    <div data-mdb-input-init class="form-outline form-white">
                                                        <input type="text" id="typeExp" class="form-control form-control-lg"
                                                               placeholder="MM/YYYY" size="7" id="exp" minlength="7" maxlength="7" />
                                                        <label class="form-label" for="typeExp">Expiration</label>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div data-mdb-input-init class="form-outline form-white">
                                                        <input type="password" id="typeText" class="form-control form-control-lg"
                                                               placeholder="&#9679;&#9679;&#9679;" size="1" minlength="3" maxlength="3" />
                                                        <label class="form-label" for="typeText">Cvv</label>
                                                    </div>
                                                </div>
                                            </div>

                                            <hr class="my-4">

                                            <a data-mdb-button-init data-mdb-ripple-init class="btn btn-info btn-block btn-lg">
                                                <input type="submit" value="@Model.SumProduct ₽" class="d-flex justify-content-between"/>
                                            </a>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

TheUltimateGamingPlatform.Web/Pages/GameDetails.cshtml
@page
@model TheUltimateGamingPlatform.Web.Pages.GameDetailsModel

@if (Model.Game is not null)
{
    <div class="container py-5">
        <div class="row">
            <div class="col-lg-6">
                <div id="productCarousel" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="@Model.Game.PreviewImg" class="d-block w-100" alt="@Model.Game.Title" />
                        </div>
                        @if (Model.Game.GameContents is not null && Model.Game.GameContents.Count != 0)
                        {
                            @for (int i = 0; i < Model.Game.GameContents.Count; i++)
                            {
                                <div class="carousel-item">
                                    <img src="@Model.Game.GameContents[i].UrlContent" class="d-block w-100" controls />
                                </div>
                            }
                        }
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#productCarousel"
                            data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#productCarousel"
                            data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    </button>
                </div>
            </div>
            <div class="col-lg-6">
                <h2 class="fw-bold">@Model.Game.Title</h2>
                <h5>Жанры: </h5>
                <ul>
                    @foreach (var genres in Model.Game.Genres)
                    {
                        <li>@genres.Title</li>
                    }
                </ul>
                <h3 class="my-4">@Model.Game.Price ₽</h3>
                <p class="mb-4">
                    @Model.Game.Description
                </p>
                <div class="d-flex gap-3 mb-4">
                    @if (Model.IsPurchased)
                    {
                        <button type="button" class="btn btn-outline-info">Товар уже куплен</button>
                    }
                    else if (Model.IsContainsInCart)
                    {
                        <button type="button" class="btn btn-outline-danger">Товар уже добавлен в корзину</button>
                    }
                    else
                    {
                        <form method="post">
                            <input type="hidden" name="id" value="@Model.Game.Id" />
                            <input type="submit" class="btn btn-success" value="Добавить в корзину" />
                        </form>
                    }
                </div>
                <div>
                    @if (!Model.IsPurchased)
                    {
                        @if (Model.IsWishList)
                        {
                            <button type="button" class="btn btn-outline-danger">Игра уже есть в списке желаемого</button>
                        }
                        else
                        {
                            <form method="post" asp-page-handler="AddWishList">
                                <input type="hidden" name="id" value="@Model.Game.Id" />
                                <input class="btn btn-primary" type="submit" value="Добавить в список желаемого" />
                            </form>
                        }
                    }

                </div>
            </div>



            <h5>Системные требования</h5>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Минимальные требования</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">ОС</th>
                        <td>@Model.Game.MinimumSystemRequirement.OS</td>
                    </tr>
                    <tr>
                        <th scope="row">Процессор</th>
                        <td>@Model.Game.MinimumSystemRequirement.Processor</td>
                    </tr>
                    <tr>
                        <th scope="row">RAM</th>
                        <td>@Model.Game.MinimumSystemRequirement.Memory</td>
                    </tr>
                    <tr>
                        <th scope="row">Жёсткий диск</th>
                        <td>@Model.Game.MinimumSystemRequirement.HardDrive</td>
                    </tr>

                    @if (Model.Game.MinimumSystemRequirement.VideoCard is not null)
                    {
                        <tr>
                            <th scope="row">Видео карта</th>
                            <td>@Model.Game.MinimumSystemRequirement.VideoCard</td>
                        </tr>
                    }

                    @if (Model.Game.MinimumSystemRequirement.DirectX is not null)
                    {
                        <tr>
                            <th scope="row">DirectX</th>
                            <td>@Model.Game.MinimumSystemRequirement.DirectX</td>
                        </tr>
                    }

                    @if (Model.Game.MinimumSystemRequirement.VR is not null)
                    {
                        <tr>
                            <th scope="row">VR</th>
                            <td>@Model.Game.MinimumSystemRequirement.VR</td>
                        </tr>
                    }

                    @if (Model.Game.MinimumSystemRequirement.Additionally is not null)
                    {
                        <tr>
                            <th scope="row">Прочее</th>
                            <td>@Model.Game.MinimumSystemRequirement.Additionally</td>
                        </tr>
                    }

                    @if (Model.Game.MinimumSystemRequirement.Network is not null)
                    {
                        <tr>
                            <th scope="row">Сеть</th>
                            <td>@Model.Game.MinimumSystemRequirement.Network</td>
                        </tr>
                    }

                    @if (Model.Game.MinimumSystemRequirement.SoundCard is not null)
                    {
                        <tr>
                            <th scope="row">Звуковая карта</th>
                            <td>@Model.Game.MinimumSystemRequirement.SoundCard</td>
                        </tr>
                    }
            </table>


            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Рекомендованные требования</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">ОС</th>
                        <td>@Model.Game.RecommendedSystemRequirement.OS</td>
                    </tr>
                    <tr>
                        <th scope="row">Процессор</th>
                        <td>@Model.Game.RecommendedSystemRequirement.Processor</td>
                    </tr>
                    <tr>
                        <th scope="row">RAM</th>
                        <td>@Model.Game.RecommendedSystemRequirement.Memory</td>
                    </tr>
                    <tr>
                        <th scope="row">Жёсткий диск</th>
                        <td>@Model.Game.RecommendedSystemRequirement.HardDrive</td>
                    </tr>

                    @if (Model.Game.RecommendedSystemRequirement.VideoCard is not null)
                    {
                        <tr>
                            <th scope="row">Видео карта</th>
                            <td>@Model.Game.RecommendedSystemRequirement.VideoCard</td>
                        </tr>
                    }

                    @if (Model.Game.RecommendedSystemRequirement.DirectX is not null)
                    {
                        <tr>
                            <th scope="row">DirectX</th>
                            <td>@Model.Game.MinimumSystemRequirement.DirectX</td>
                        </tr>
                    }

                    @if (Model.Game.RecommendedSystemRequirement.VR is not null)
                    {
                        <tr>
                            <th scope="row">VR</th>
                            <td>@Model.Game.RecommendedSystemRequirement.VR</td>
                        </tr>
                    }

                    @if (Model.Game.RecommendedSystemRequirement.Additionally is not null)
                    {
                        <tr>
                            <th scope="row">Прочее</th>
                            <td>@Model.Game.RecommendedSystemRequirement.Additionally</td>
                        </tr>
                    }

                    @if (Model.Game.RecommendedSystemRequirement.Network is not null)
                    {
                        <tr>
                            <th scope="row">Сеть</th>
                            <td>@Model.Game.RecommendedSystemRequirement.Network</td>
                        </tr>
                    }

                    @if (Model.Game.RecommendedSystemRequirement.SoundCard is not null)
                    {
                        <tr>
                            <th scope="row">Звуковая карта</th>
                            <td>@Model.Game.RecommendedSystemRequirement.SoundCard</td>
                        </tr>
                    }
            </table>
        </div>
    </div>
}
else
{
    <h1>Игры не была найдена</h1>
}

TheUltimateGamingPlatform.Web/Pages/Index.cshtml
@page
@model TheUltimateGamingPlatform.Web.Pages.IndexModel

<div class="container">
    <h1 class="mt-3">Игры: </h1>
    <div class="row row-cols-4 gap-3 mt-4">
        @foreach (var game in Model.Games)
        {
            <div class="card" style="width: 18rem;">
                <img src="@game.PreviewImg" class="card-img-top" alt="@game.Title">
                <div class="card-body">
                    <h5 class="card-title">@game.Title</h5>
                    <p class="card-text">@game.Price</p>
                    <a asp-page="GameDetails" asp-route-id="@game.Id" class="btn btn-primary">Купить</a>
                </div>
            </div>
        }
    </div>
</div>

TheUltimateGamingPlatform.Web/Pages/Library.cshtml
@page
@model TheUltimateGamingPlatform.Web.Pages.LibraryModel


<div class="container">
    <h1 class="mt-3">Библиотека Игр: </h1>
    <div class="row row-cols-4 gap-3 mt-4">
        @foreach (var game in Model.Games)
        {
            <div class="card" style="width: 18rem;">
                <img src="@game.PreviewImg" class="card-img-top" alt="@game.Title">
                <div class="card-body">
                    <h5 class="card-title">@game.Title</h5>
                </div>
            </div>
        }
    </div>
</div>

TheUltimateGamingPlatform.Web/Pages/Profile.cshtml
@page
@model TheUltimateGamingPlatform.Web.Pages.ProfileModel

<h1>Profile</h1>

TheUltimateGamingPlatform.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>@ViewBag.Title</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" asp-page="/Index">The Ultimate Gaming Platform</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Магазин
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" asp-page="/Shop/PopularGames">Популярное</a></li>
                            <li><a class="dropdown-item" asp-page="/Shop/RecommendationGames">Рекомендации</a></li>
                            <li><a class="dropdown-item" asp-page="/Shop/WishList">Список желаемого</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" asp-page="/Library">Библиотека</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" asp-page="/Profile">Профиль</a>
                    </li>
                </ul>
                <div>
                    <a class="btn btn-outline-light" asp-page="/Cart">Корзина</a>
                </div>
            </div>
        </div>
    </nav>
    @RenderBody()
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

TheUltimateGamingPlatform.Web/Pages/Shop/PopularGames.cshtml
@page
@model TheUltimateGamingPlatform.Web.Pages.Shop.PopularGamesModel

<div class="container">
    <h1 class="mt-3">Популярные игры: </h1>
    <div class="row row-cols-4 gap-3 mt-4">
        @if (Model.Games is null || Model.Games.Count == 0)
        {
            <h1>Нет пока популярных игр</h1>
        }
        else
        {
            @foreach (var game in Model.Games)
            {
                <div class="card" style="width: 18rem;">
                    <img src="@game.PreviewImg" class="card-img-top" alt="@game.Title">
                    <div class="card-body">
                        <h5 class="card-title">@game.Title</h5>
                    </div>
                </div>
            }
        }
    </div>
</div>

TheUltimateGamingPlatform.Web/Pages/Shop/RecommendationGames.cshtml
@page
@model TheUltimateGamingPlatform.Web.Pages.Shop.RecommendationGamesModel

<div class="container">
    <h1 class="mt-3">Рекомендации: </h1>
    <div class="row row-cols-4 gap-3 mt-4">
        @if (Model.Games is null || Model.Games.Count == 0)
        {
            <h1>Нет пока игр в списке желаемого</h1>
        }
        else
        {
            @foreach (var game in Model.Games)
            {
                <div class="card" style="width: 18rem;">
                    <img src="@game.PreviewImg" class="card-img-top" alt="@game.Title">
                    <div class="card-body">
                        <h5 class="card-title">@game.Title</h5>
                    </div>
                </div>
            }
        }
    </div>
</div>